// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
export const parser = Parser.deserialize({
  version: 13,
  states: "!^OVQPOOO[QQO'#C^QOQPOOOdQPO'#C`OOQO'#Cg'#CgOiQQO,58xOqQSO,58zOOQO-E6e-E6eOOQO'#Cb'#CbOOQO1G.f1G.f",
  stateData: "!S~O^OS~ORPO~OTRO[QX~O_UO~OTRO[Qa~OVWOWWOXWOYWO~OXY~",
  goto: "m[PP]P`PdPPPPgRQOTSPTRXUQTPRVT",
  nodeNames: "⚠ Config ConfigLine PluginClass Arg ArgName Value String Int Boolean BareValue",
  maxTerm: 15,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "8a~RpX^#Vpq#Vrs#zuv$ivw$i}!O%d!O!P$i!P!Q$i!Q![&_![!]$i!_!`'[!a!b$i!b!c$i!c!h'a!h!i*W!i!v'a!v!w/j!w!}'a#R#S'a#T#Y'a#Y#Z1t#Z#h'a#h#i6V#i#o'a#y#z#V$f$g#V#BY#BZ#V$IS$I_#V$I|$JO#V$JT$JU#V$KV$KW#V&FU&FV#V~#[Y^~X^#Vpq#V#y#z#V$f$g#V#BY#BZ#V$IS$I_#V$I|$JO#V$JT$JU#V$KV$KW#V&FU&FV#V~#}TOr#zrs$^s#O#z#O#P$c#P~#z~$cOV~~$fPO~#zS$n[YSuv$ivw$i}!O$i!O!P$i!P!Q$i!Q![$i![!]$i!a!b$i!b!c$i!c!}$i#R#S$i#T#o$i~%i[YSuv$ivw$i}!O$i!O!P$i!P!Q$i!Q![&_![!]$i!a!b$i!b!c$i!c!}$i#R#S$i#T#o$i~&f[W~YSuv$ivw$i}!O$i!O!P$i!P!Q$i!Q![&_![!]$i!a!b$i!b!c$i!c!}$i#R#S$i#T#o$i~'aO_~V'j[TQRPYSuv$ivw$i}!O$i!O!P(`!P!Q$i!Q!['a![!]$i!a!b$i!b!c$i!c!}'a#R#S'a#T#o'aT(e[YSuv$ivw$i}!O$i!O!P$i!P!Q$i!Q![)Z![!]$i!a!b$i!b!c$i!c!})Z#R#S)Z#T#o)ZT)b[RPYSuv$ivw$i}!O$i!O!P(`!P!Q$i!Q![)Z![!]$i!a!b$i!b!c$i!c!})Z#R#S)Z#T#o)ZV*a]TQRPYSuv$ivw$i}!O$i!O!P(`!P!Q$i!Q!['a![!]$i!a!b$i!b!c$i!c!d+Y!d!}'a#R#S'a#T#o'aV+c^TQRPYSuv$ivw$i}!O$i!O!P(`!P!Q$i!Q!['a![!]$i!a!b$i!b!c$i!c!n'a!n!o,_!o!}'a#R#S'a#T#o'aV,h^TQRPYSuv$ivw$i}!O$i!O!P(`!P!Q$i!Q!['a![!]$i!a!b$i!b!c$i!c!u'a!u!v-d!v!}'a#R#S'a#T#o'aV-m^TQRPYSuv$ivw$i}!O$i!O!P(`!P!Q$i!Q!['a![!]$i!a!b$i!b!c$i!c!g'a!g!h.i!h!}'a#R#S'a#T#o'aV.t[TQRPXSYSuv$ivw$i}!O$i!O!P(`!P!Q$i!Q!['a![!]$i!a!b$i!b!c$i!c!}'a#R#S'a#T#o'aV/s^TQRPYSuv$ivw$i}!O$i!O!P(`!P!Q$i!Q!['a![!]$i!a!b$i!b!c$i!c!t'a!t!u0o!u!}'a#R#S'a#T#o'aV0x^TQRPYSuv$ivw$i}!O$i!O!P(`!P!Q$i!Q!['a![!]$i!a!b$i!b!c$i!c!w'a!w!x-d!x!}'a#R#S'a#T#o'aV1}]TQRPYSuv$ivw$i}!O$i!O!P(`!P!Q$i!Q!['a![!]$i!a!b$i!b!c$i!c!}'a#R#S'a#T#U2v#U#o'aV3P^TQRPYSuv$ivw$i}!O$i!O!P(`!P!Q$i!Q!['a![!]$i!a!b$i!b!c$i!c!}'a#R#S'a#T#`'a#`#a3{#a#o'aV4U^TQRPYSuv$ivw$i}!O$i!O!P(`!P!Q$i!Q!['a![!]$i!a!b$i!b!c$i!c!}'a#R#S'a#T#g'a#g#h5Q#h#o'aV5Z^TQRPYSuv$ivw$i}!O$i!O!P(`!P!Q$i!Q!['a![!]$i!a!b$i!b!c$i!c!}'a#R#S'a#T#X'a#X#Y.i#Y#o'aV6`^TQRPYSuv$ivw$i}!O$i!O!P(`!P!Q$i!Q!['a![!]$i!a!b$i!b!c$i!c!}'a#R#S'a#T#f'a#f#g7[#g#o'aV7e^TQRPYSuv$ivw$i}!O$i!O!P(`!P!Q$i!Q!['a![!]$i!a!b$i!b!c$i!c!}'a#R#S'a#T#i'a#i#j5Q#j#o'a",
  tokenizers: [0, 1, 2],
  topRules: {"Config":[0,1]},
  tokenPrec: 47
})
