// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Config = 1,
  ConfigLine = 2,
  PluginClass = 3,
  Arg = 4,
  ArgName = 5,
  Value = 6,
  String = 7,
  Int = 8,
  Boolean = 9,
  BareValue = 10
